# Random Forest - CompanyData

In [1]:
#Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Import Dataset
company = pd.read_csv('Company_Data.csv')
company

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0     9.50        138      73           11         276    120       Bad   42   
1    11.22        111      48           16         260     83      Good   65   
2    10.06        113      35           10         269     80    Medium   59   
3     7.40        117     100            4         466     97    Medium   55   
4     4.15        141      64            3         340    128       Bad   38   
..     ...        ...     ...          ...         ...    ...       ...  ...   
395  12.57        138     108           17         203    128      Good   33   
396   6.14        139      23            3          37    120    Medium   55   
397   7.41        162      26           12         368    159    Medium   40   
398   5.94        100      79            7         284     95       Bad   50   
399   9.71        134      37            0          27    120      Good   49   

     Education Urban   US  
0           17   Yes  Yes  
1           10   Yes  Yes  
2           12   Yes  Yes  
3           14   Yes  Yes  
4           13   Yes   No  
..         ...   ...  ...  
395         14   Yes  Yes  
396         11    No  Yes  
397         18   Yes  Yes  
398         12   Yes  Yes  
399         16   Yes  Yes  

[400 rows x 11 columns]

In [3]:
company.loc[company.Sales >= 8.5, 'sales'] = 'high'
company.loc[company.Sales < 8.5, 'sales'] = 'low'

In [4]:
company.drop('Sales', 1, inplace= True)

C:\Users\HP\AppData\Local\Temp\ipykernel_23100\1602165683.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  company.drop('Sales', 1, inplace= True)


In [5]:
company.isnull().sum()

CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
ShelveLoc      0
Age            0
Education      0
Urban          0
US             0
sales          0
dtype: int64

In [6]:
from sklearn import preprocessing

In [7]:
label_encoder = preprocessing.LabelEncoder()
company['US'] = label_encoder.fit_transform(company['US'])
company['US'].unique()

array([1, 0])

In [8]:
label_encoder = preprocessing.LabelEncoder()
company['Urban'] = label_encoder.fit_transform(company['Urban'])

In [9]:
label_encoder = preprocessing.LabelEncoder()
company['ShelveLoc'] = label_encoder.fit_transform(company['ShelveLoc'])

In [10]:
colnames = list(company.columns)
predictors = colnames[0:10]
target = colnames[10]

In [11]:
predictors

['CompPrice',
 'Income',
 'Advertising',
 'Population',
 'Price',
 'ShelveLoc',
 'Age',
 'Education',
 'Urban',
 'US']

In [12]:
target

'sales'

In [13]:
label_encoder = preprocessing.LabelEncoder()
company['sales'] = label_encoder.fit_transform(company['sales'])

In [14]:
X = company [predictors]
Y = company [target]

In [15]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
rf = RandomForestClassifier(n_jobs=2, oob_score=True,n_estimators=1000,criterion="entropy")

In [17]:
rf.fit(X,Y)

RandomForestClassifier(criterion='entropy', n_estimators=1000, n_jobs=2,
                       oob_score=True)

In [18]:
rf.estimator_

DecisionTreeClassifier()

In [19]:
rf.classes_

array([0, 1])

In [20]:
rf.n_classes_

2

In [21]:
rf.n_features_in_

10

In [22]:
rf.n_outputs_

1

In [23]:
company['rf_pred'] = rf.predict(X)

In [24]:
from sklearn.metrics import confusion_matrix

In [25]:
confusion_matrix(company['sales'],company['rf_pred'])

array([[143,   0],
       [  0, 257]], dtype=int64)